version: '3'
services:
  node:
    image: node:10-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    command: "npm run dev"
    ports:
      - "8080:8080"
